// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iyfwfwryibqfqetmbpqq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml5Zndmd3J5aWJxZnFldG1icHFxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkyMzE5NDcsImV4cCI6MjA3NDgwNzk0N30._5M8F9rW9pC7yfLmnnF1RbkQWGswqrDmm0c0P48bN5M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});